apiVersion: v1
kind: Service
metadata:
  name: django-messaging-active
  labels:
    app: django-messaging
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: django-messaging
    version: "1.0"